

export const FALLBACK_ARTICLES = [
  {
    id: 'art-1',
    category: 'market',
    categoryLabel: 'Bandung CBD Market',
    title: 'Why Asia Afrika Remains Bandung’s Preeminent Business Address',
    excerpt: 'Exploring the historical significance, infrastructure density, and psychological advantage of establishing a corporate presence in Bandung’s financial heart.',
    author: 'Hendrik Wijaya, Lead Market Analyst',
    date: 'July 28, 2026',
    readTime: '4 min read',
    image: '/SPACES/PREMIUM OFFICE/Premium Office.webp?v=20260822',
  },
  {
    id: 'art-2',
    category: 'sustainability',
    categoryLabel: 'Sustainability',
    title: 'Net-Zero Energy Buildings: Integrating Solar Membranes & Passive Cooling',
    excerpt: 'How modern architectural engineering reduces thermal load, lowers HVAC power consumption, and achieves LEED Platinum standards in tropical urban centers.',
    author: 'Dr. Sarah Lin, Principal Environmental Engineer',
    date: 'July 22, 2026',
    readTime: '6 min read',
    image: '/BUILDING/ChatGPT%20Image%20Jul%2029,%202026,%2003_09_51%20PM.webp?v=20260822',
  },
  {
    id: 'art-3',
    category: 'architecture',
    categoryLabel: 'Architecture & Design',
    title: 'The SOHO Revolution: Blending Private Residence & Corporate Office',
    excerpt: 'A deep dive into dual-purpose spatial planning, acoustics, and zoning strategies for modern entrepreneurs who live and work under one roof.',
    author: 'Marcus Vance, Senior Architect',
    date: 'July 15, 2026',
    readTime: '5 min read',
    image: '/SPACES/SOHO/SOHO 01.webp?v=20260822',
  },
  {
    id: 'art-4',
    category: 'workplace',
    categoryLabel: 'Workplace Trends',
    title: 'Acoustic Ergonomics: Designing Noise-Controlled Executive Spaces',
    excerpt: 'Balancing collaborative open layouts with private acoustic focus pods to maximize cognitive focus and eliminate workplace fatigue.',
    author: 'Elena Rostova, Workplace Ergonomist',
    date: 'July 08, 2026',
    readTime: '4 min read',
    image: '/SPACES/SERVICED OFFICE/1.webp?v=20260822',
  },
  {
    id: 'art-5',
    category: 'architecture',
    categoryLabel: 'Architecture & Design',
    title: 'Smart Automated Parking: The Future of High-Density Commercial Real Estate',
    excerpt: 'How vertical mechanical car lifts increase parking capacity by 300% while offering smooth, contactless vehicle delivery for tenants.',
    author: 'Ir. Budi Santoso, Infrastructure Lead',
    date: 'June 30, 2026',
    readTime: '3 min read',
    image: '/LOGO/parking-lift.webp?v=20260822',
  },
  {
    id: 'art-6',
    category: 'market',
    categoryLabel: 'Bandung CBD Market',
    title: 'Tenant Ecosystem Dynamics: How Shared Corporate Neighbors Drive Value',
    excerpt: 'Analyzing how co-locating near multinational financial institutions, tech firms, and legal advisories boosts brand credibility and referral networks.',
    author: 'Hendrik Wijaya, Lead Market Analyst',
    date: 'June 20, 2026',
    readTime: '5 min read',
    image: '/SPACES/PREMIUM OFFICE/Premium Office 06.webp?v=20260822',
  },
];

export const FALLBACK_ARTICLE_DETAILS = {
  'art-1': {
    id: 'art-1',
    categoryLabel: 'Bandung CBD Market',
    title: 'Why Asia Afrika Remains Bandung’s Preeminent Business Address',
    subtitle: 'Exploring the historical significance, infrastructure density, and psychological advantage of establishing a corporate presence in Bandung’s financial heart.',
    author: 'Hendrik Wijaya',
    role: 'Lead Market Analyst, HQuarters Research',
    date: 'July 28, 2026',
    readTime: '4 min read',
    image: '/location_map.webp?v=20260822',
    imageCaption: 'Historical & modern financial corridor at Jl. Asia Afrika No. 158, Bandung CBD.',
  },
  'art-2': {
    id: 'art-2',
    categoryLabel: 'Sustainability',
    title: 'Net-Zero Energy Buildings: Integrating Solar Membranes & Passive Cooling',
    subtitle: 'How modern architectural engineering reduces thermal load, lowers HVAC power consumption, and achieves LEED Platinum standards in tropical urban centers.',
    author: 'Dr. Sarah Lin',
    role: 'Principal Environmental Engineer',
    date: 'July 22, 2026',
    readTime: '6 min read',
    image: '/architectural_hero_bg.webp?v=20260822',
    imageCaption: 'Energy-efficient facade system designed for maximum thermal dissipation.',
  },
  'art-3': {
    id: 'art-3',
    categoryLabel: 'Architecture & Design',
    title: 'The SOHO Revolution: Blending Private Residence & Corporate Office',
    subtitle: 'A deep dive into dual-purpose spatial planning, acoustics, and zoning strategies for modern entrepreneurs who live and work under one roof.',
    author: 'Marcus Vance',
    role: 'Senior Architect & Spatial Planner',
    date: 'July 15, 2026',
    readTime: '5 min read',
    image: '/soho_office.webp?v=20260822',
    imageCaption: 'Dual-volume SOHO layout balancing executive workspace with residence.',
  },
  'art-4': {
    id: 'art-4',
    categoryLabel: 'Workplace Trends',
    title: 'Acoustic Ergonomics: Designing Noise-Controlled Executive Spaces',
    subtitle: 'Balancing collaborative open layouts with private acoustic focus pods to maximize cognitive focus and eliminate workplace fatigue.',
    author: 'Elena Rostova',
    role: 'Workplace Ergonomist',
    date: 'July 08, 2026',
    readTime: '4 min read',
    image: '/serviced_office.webp?v=20260822',
    imageCaption: 'Acoustically dampened meeting and focus rooms engineered for concentration.',
  },
  'art-5': {
    id: 'art-5',
    categoryLabel: 'Architecture & Design',
    title: 'Smart Automated Parking: The Future of High-Density Commercial Real Estate',
    subtitle: 'How vertical mechanical car lifts increase parking capacity by 300% while offering smooth, contactless vehicle delivery for tenants.',
    author: 'Ir. Budi Santoso',
    role: 'Infrastructure & Mechanical Lead',
    date: 'June 30, 2026',
    readTime: '3 min read',
    image: '/LOGO/parking-lift.webp?v=20260822',
    imageCaption: 'Mechanical automated parking lift installed at HQuarters Business Residence.',
  },
  'art-6': {
    id: 'art-6',
    categoryLabel: 'Bandung CBD Market',
    title: 'Tenant Ecosystem Dynamics: How Shared Corporate Neighbors Drive Value',
    subtitle: 'Analyzing how co-locating near multinational financial institutions, tech firms, and legal advisories boosts brand credibility and referral networks.',
    author: 'Hendrik Wijaya',
    role: 'Lead Market Analyst',
    date: 'June 20, 2026',
    readTime: '5 min read',
    image: '/premium_office.webp?v=20260822',
    imageCaption: 'Enterprise office floor hosting global financial and professional institutions.',
  },
  featured: {
    id: 'featured',
    categoryLabel: 'Workplace Trends',
    title: 'The Evolution of Hybrid Headquarters: Designing Offices for the Next Decade',
    subtitle: 'How modern corporations are shifting from static workstations to dynamic, hospitality-driven hub offices that foster collaboration, high focus, and employee wellness.',
    author: 'Marcus Vance',
    role: 'Principal Architect & Urban Planner',
    date: 'August 2026',
    readTime: '5 min read',
    image: '/blog_hero.webp?v=20260822',
    imageCaption: 'HQuarters executive atrium showcasing natural daylighting and biophilic elements.',
  },
};
